dist: bionic

language: php

php:
  - 7.4

branches:
  only:
    - master
    - dev

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction
  - cp .env.example .env
  - php laravel/artisan key:generate
  - php laravel/artisan vendor:publish --provider="Zablose\Rap\RapServiceProvider" --tag=migrations

script: php vendor/bin/phpunit
