dist: bionic

language: php

php:
  - 7.4

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction
  - php laravel/artisan vendor:publish --provider="Zablose\Rap\RapServiceProvider" --tag=migrations

script: php vendor/bin/phpunit
