services:

  rap-nginx:
    image: zablose/nginx:1.27
    build:
      context: ./zdi/
      dockerfile: files/nginx.df
      args:
        - ARG_DIR_WEB=${ZDI_DIR_WEB}
        - ARG_ENV=${ZDI_ENV}
        - ARG_TIMEZONE=${ZDI_TIMEZONE}
        - ARG_USER_GROUP_ID=${ZDI_USER_GROUP_ID}
        - ARG_USER_GROUP_NAME=${ZDI_USER_GROUP_NAME}
        - ARG_USER_ID=${ZDI_USER_ID}
        - ARG_USER_NAME=${ZDI_USER_NAME}
    container_name: rap-nginx
    environment:
      ZDI_CONTAINER_NAME: rap-nginx
      ZDI_PHP_FPM_HOST: rap-php-fpm
    ports:
      - '${ZDI_HOST_IP}:80:80'
      - '${ZDI_HOST_IP}:443:443'
    volumes:
      - ./.env:/home/.env
      - ./:${ZDI_DIR_WEB}/
    logging:
      driver: syslog
      options:
        syslog-address: 'tcp://${ZDI_HOST_IP}:514'
        tag: 'docker/rap-nginx'
    depends_on:
      - rap-php-fpm
      - rap-rsyslog
    networks:
      - default

  rap-php-fpm:
    image: zablose/php-fpm:${ZDI_VERSION_PHP}
    build:
      context: ./zdi/
      dockerfile: files/php-fpm.df
      args:
        - ARG_ADD_COMPOSER=${ZDI_ADD_COMPOSER}
        - ARG_ADD_LARAVEL=${ZDI_ADD_LARAVEL}
        - ARG_DIR_WEB=${ZDI_DIR_WEB}
        - ARG_ENV=${ZDI_ENV}
        - ARG_TIMEZONE=${ZDI_TIMEZONE}
        - ARG_USER_GROUP_ID=${ZDI_USER_GROUP_ID}
        - ARG_USER_GROUP_NAME=${ZDI_USER_GROUP_NAME}
        - ARG_USER_ID=${ZDI_USER_ID}
        - ARG_USER_NAME=${ZDI_USER_NAME}
        - ARG_VERSION_COMPOSER=${ZDI_VERSION_COMPOSER}
        - ARG_VERSION_PHP=${ZDI_VERSION_PHP}
    container_name: rap-php-fpm
    environment:
      ZDI_CONTAINER_NAME: rap-php-fpm
      ZDI_DB_HOSTNAME: rap-mariadb
    volumes:
      - ./.env:/home/.env
      - $HOME/.composer/cache/:/home/${ZDI_USER_NAME}/.composer/cache/
      - ./:${ZDI_DIR_WEB}/
      - ./post-setup.sh:/home/${ZDI_USER_NAME}/post-setup.sh
    logging:
      driver: syslog
      options:
        syslog-address: 'tcp://${ZDI_HOST_IP}:514'
        tag: 'docker/rap-php-fpm'
    depends_on:
      - rap-mariadb
      - rap-rsyslog
    networks:
      - default

  rap-mariadb:
    image: zablose/mariadb:10.11.6
    build:
      context: ./zdi/
      dockerfile: files/mariadb.df
      args:
        - ARG_ENV=${ZDI_ENV}
        - ARG_TIMEZONE=${ZDI_TIMEZONE}
        - ARG_USER_GROUP_ID=${ZDI_USER_GROUP_ID}
        - ARG_USER_GROUP_NAME=${ZDI_USER_GROUP_NAME}
        - ARG_USER_ID=${ZDI_USER_ID}
        - ARG_USER_NAME=${ZDI_USER_NAME}
    container_name: rap-mariadb
    environment:
      ZDI_CONTAINER_NAME: rap-mariadb
    logging:
      driver: syslog
      options:
        syslog-address: 'tcp://${ZDI_HOST_IP}:514'
        tag: 'docker/rap-mariadb'
    volumes:
      - ./.env:/home/.env
      - rap_db:/var/lib/mysql/
    depends_on:
      - rap-rsyslog
    networks:
      - default

  rap-rsyslog:
    image: zablose/rsyslog:3.19.1
    build:
      context: ./zdi/
      dockerfile: files/rsyslog.df
    container_name: rap-rsyslog
    ports:
      - '${ZDI_HOST_IP}:514:514'
    volumes:
      - ./laravel/storage/logs/:/var/log/
    networks:
      - default

volumes:
  rap_db:

networks:
  default:
    name: zdev_default
    driver: bridge
    external: true
